Added change proposal support
Metatavu/lipsanen-project-management-spec pull request #22
Opened 2024-05-03 08:16 UTC by Daniilmass

Resolves #21

2024-05-03 08:53 UTC, kaeline commented on swagger.yaml
> +        - Change Proposals
Tags should be one word i think for the code generation

2024-05-03 08:53 UTC, kaeline commented on swagger.yaml
> +    ChangeProposal:
Where does this object keep the actual proposed change? E.g new task object with changed fields?

2024-05-06 06:01 UTC, kaeline commented on swagger.yaml
> +          description: The ID of the user who created the change proposal
We could just use metadata for this purposes?

2024-05-06 07:23 UTC, kaeline approved these changes

2024-05-15 05:50 UTC, lauriLukkarinen requested changes

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +          description: List of change proposals for the milestone task
```suggestion
          description: List of change proposals
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +      description: Get all change proposals for a milestone task sort from old to new
```suggestion
      summary: List change proposals within a milestone
      description: Lists change proposals within a milestone. Proposals are sorted from earliest to latest created.
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +      description: Get a specific change proposal for a milestone task
```suggestion
      summary: Find a specific change proposal within a milestone
      description: Find a specific change proposal within a milestone
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +      description: Update a specific change proposal for a milestone task
```suggestion
      summary: Update a specific change proposal within a milestone
      description: Update a specific change proposal within a milestone
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +      description: Create a new change proposal for a milestone task
```suggestion
      summary: Create a new change proposal within a milestone
      description: Create a new change proposal within a milestone
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +          description: Updated change proposal for the milestone task
```suggestion
          description: Updated change proposal
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +          description: Specific change proposal for the milestone task
```suggestion
          description: Found change proposal
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +          description: Created change proposal for the milestone task
```suggestion
          description: Created change proposal
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +      description: Delete a specific change proposal for a milestone task
```suggestion
      summary: Delete a specific change proposal within a milestone
      description: Deletes a specific change proposal within a milestone
```

2024-05-15 05:50 UTC, lauriLukkarinen commented on swagger.yaml
> +        - taskId
Should reason also be required?
```suggestion
      required:
        - status
        - taskId
        - reason
```

2024-05-16 10:11 UTC, lauriLukkarinen approved these changes

2024-05-16 11:03 UTC, merged